### ISSUE TITLE
Blaze Burner not working with lava

### ISSUE THREAD

**Issue by greatmonkey** [EnigmaticaModpacks/Enigmatica9#1011]
### Modpack Version

1.23.2

### Describe your issue.

The create blaze burner is not working with lava being auto piped into it, after giving it a straw.  It will fill up with lava but will not work for the mixer.  IT will work if you use a bucket of lava on it but after the burn timer runs out, it will stop working as if it has nothing to burn.
Tested this in a test world and found it would not work for anything from potions to Rubber, or Chocolate, etc

### Crash Report

n/a

### Latest Log

n/a

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

greatmonkey

**Comment by MuteTiefling** [comment]
Thanks for the report! I'm afraid this is intentional, however, and should be clear from EMI that liquid lava is not a valid fuel. 

The reason for this is simply because it'd be a bit too easy. If you want to use the cheap, free, easy lava method, you'll need to use buckets and therefore find a way of dealing with the buckets themselves. 

Valid Fuels: https://github.com/EnigmaticaModpacks/Enigmatica9/blob/ee32d0e20e654667bdeb6a891254bb3d753ddcd8/kubejs/server_scripts/constants/fuel_properties.js#L7

**Comment by greatmonkey** [comment]
so the quest gives you a straw to trick you into thinking it will work huh? lol

**Comment by MuteTiefling** [comment]
The quest gives you a straw to indicate that it can take liquid fuels. Look at uses for the straw to see what's allowed.
