### ISSUE TITLE
[Mod Suggestion] Thermal Series

### ISSUE THREAD

**Issue by Kanzaji** [EnigmaticaModpacks/Enigmatica9#142]
### URL

https://www.curseforge.com/minecraft/mc-mods/thermal-expansion

### Why would you like the mod added?

![obraz](https://user-images.githubusercontent.com/60540476/203640766-80229ca6-5b05-4f04-8ef9-f54746cac62e.png)

Thermal for 1.19.2 is supposed to be soon:tm: So I'm just gonna leave this here

**Comment by Kanzaji** [comment]
Thermal mods are out for 1.19.2 \o/

**Comment by NielsPilgaard** [comment]
woot!

**Comment by NielsPilgaard** [comment]
Not sure about Cultivation 🤔

**Comment by MuteTiefling** [comment]
Looks like our prior issues with Thermal Cultivation have been resolved, actually.

There's a config to disable the villager trades, one to disable seed drops from grass. And it adds some nice qol stuff like the watering can, the beekeeper's suit, and actual foods rather than just a bunch of random ingredients, some of which look really fun (witch cake that gives potion effects, stew that increase XP gained

**Comment by MuteTiefling** [comment]
also, AU should help us clean up/unify all the various food item recipes quite easily >.>
