### ISSUE TITLE
Kubejs errors

### ISSUE THREAD

**Issue by DJteaCosy** [EnigmaticaModpacks/Enigmatica9#154]
### Modpack Version

1.3.0

### Describe your issue.

Occasionally when entering a singleplayer world, a kubejs error warning is shown in chat, and a log is generated. I've included a link to the error log below

https://paste.ee/p/NPW56

Steps to reproduce: enter a singleplayer game, every second or third attempt will generate kubejs errors

### Have you modified the modpack?

Yes

### User Modifications

Added rubidium

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

dj_teaCosy#8331

**Comment by Kanzaji** [comment]
Thanks for the report! This issue is already known, and we are trying to fix it. Hopefully next release will eliminate all of those ^^"
For now, just use /reload when those errors occur, until you will reload without them.

PS: Normally we would ask you to remove rubidium, but other people mentioned those errors without it :)
