### ISSUE TITLE
Add a Create-Torque-to-Power Transformer

### ISSUE THREAD

**Issue by sniggyfigbat** [EnigmaticaModpacks/Enigmatica9#206]
### Describe your suggestion

While I understand why there's no way to run a Create system off RF, it'd be really nice to be able to generate RF from Create torque. It'd be really cool to be able to run a base off Create steam-engines as a mid-tier energy solution.

### Why would you like this added/changed?

It'd make it much easier to build Create-first bases, rather than inevitably having to give Mechanism/IE equal billing even if one doesn't particularly like them.

**Comment by theboo** [comment]
There's been many attempts at this in the past and they always get rejected in enigmatica packs due to power loops...

Things like IE external heaters or mekanism resistive heaters being able to power a blast furnace engine and flywheel for less than 10 fe/t, then you can use that flywheel to generate hundreds of thousands of fe/t... 

I also agree it would be cool and make a ton of sense but it's far too easy to abuse these systems

**Comment by sniggyfigbat** [comment]
Ah, I see. That's a real pity, but it makes sense.

**Comment by MuteTiefling** [comment]
Now that the furnace engine no longer exists I think we could possibly revisit this idea. I'm not sure what mods exist for it currently, however.

**Comment by MuteTiefling** [comment]
https://www.curseforge.com/minecraft/mc-mods/createaddition I suppose

**Comment by MuteTiefling** [comment]
The Alternator, Rolling Mill, and Tesla Coil do seem promising. Most of the rest of it is redundant with IE, however. Might not take long to disable the unwanted stuff and integrate it, however.

**Comment by MuteTiefling** [comment]
Yeah, not too bad to integrate and remove the excess stuff.
