### ISSUE TITLE
[Suggestion] Thermal Dynamics

### ISSUE THREAD

**Issue by Gronglegrowth** [EnigmaticaModpacks/Enigmatica9#342]
### URL

https://www.curseforge.com/minecraft/mc-mods/thermal-dynamics

### Why would you like the mod added?

The rest of Thermal Series is present, so it only makes sense to include Dynamics, now that it's out.

**Comment by NielsPilgaard** [comment]
I vote yes 😄 we can always disable in Expert. @MuteTiefling thoughts?

**Comment by FooterMan15** [comment]
No Item Ducts though :(

**Comment by MuteTiefling** [comment]
I'm a bit ambivalent, to be honest. 

- It's only power and fluid.
- Power works great with Thermal machines, but in my limited testing this morning is super wonky with mekanism and enigmatic unity
- Fluid is limited to 50 mb/t with the 'basic' servo, and cap out at 8000 mb/t. Which is decent, but also can't be configured anywhere that I've found

**Comment by MuteTiefling** [comment]
Actually, for power it seems like they're just funky with Power Meters

**Comment by Darkere** [comment]
funky in what way?

**Comment by MuteTiefling** [comment]
Stick down a conduit connected to a battery or whatever. Place more than one EU crystal on it and it'll only pull from one. The rest never output their power.

For energy meter, it just doesn't like to run power through it if there's multiple things generating power.

The issues with mekanism were probably mostly due to these two things since I was making power with eu and measuring it with energy meters. I just wasn't getting power through to the mek machines in a timely manner

**Comment by NielsPilgaard** [comment]
The way I see it, this would be mostly for normal mode - Do you think that could work?

**Comment by MuteTiefling** [comment]
Sure.
