### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by Joprebond** [EnigmaticaModpacks/Enigmatica9#368]
### Modpack Version

1.6.0

### Describe your issue.

Game keeps crashing. Was just doing routine tasks around the base.

### Crash Report

https://gist.github.com/Joprebond/a6361a1205daed168fd36d71553d1f4e

### Latest Log

https://gist.github.com/Joprebond/82647d76a3d3601195a459211ff23cd0

### Have you modified the modpack?

Yes

### User Modifications

CCI

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

JoprebondOdin#5307

**Comment by theboo** [comment]
See if updating PVI on your server and client allows you to load the world

**Comment by theboo** [comment]
Kanz this is an occultism mob, we haven't yeeted them as that was the main reason for adding PVI.. is why I didn't mention that script, it only yeets vanilla mobs from the tag

**Comment by Kanzaji** [comment]
Oh wait right, its occultism! Ingore me then >.>

**Comment by Joprebond** [comment]
I already had that PVI script in there because it was stopping other crashing.

**Comment by Joprebond** [comment]
FYI i updated PVI to  per_viam_invenire-1.19.2-0.1.58-RELEASE-universal.jar per a suggestion in discord and the world still doesn't load.

**Comment by marchermans** [comment]
@Kanzaji: Hello instead of creating a weird script: How about reporting your issue to the PVI maintainers?

Then with regards to this issue: This is not a PVI issue but a Forge Bug as far as I can tell. Some mod is causing a thread interrupt in your modpack, this closes the classloaders access to the underlying jars. PVI is very carefull not to trigger the interrupt because we did in the past and we were notified about this. At the moment we don't do that anymore and you might need to start looking at other mods that can cause this.

**Comment by marchermans** [comment]
@Joprebond Question: Does this only happen after reopening a world an SP world? Or even on SMP?

**Comment by Darkere** [comment]
Crash was reported to you here: https://discord.com/channels/813822770345279549/813913279696338964/1100461068981121094
And was fixed a couple days ago. 

This seems to be a different issue entirely. 
But yeah... people need to stop making reports on discord. It gets lost so easily.

**Comment by marchermans** [comment]
> Crash was reported to you here: https://discord.com/channels/813822770345279549/813913279696338964/1100461068981121094 And was fixed a couple days ago.
> 
> This seems to be a different issue entirely. But yeah... people need to stop making reports on discord. It gets lost so easily.
> 
> > <img alt="" width="48" src="undefined//discord.com/assets/652f40427e1f5186ad54836074898279.png"><img alt="" height="14" src="/assets/ec2c34cadd4b5f4594415127380a85e6.ico"> Discord**[Discord - A New Way to Chat with Friends & Communities](https://discord.com/channels/813822770345279549/813913279696338964/1100461068981121094)**Discord is the easiest way to communicate over voice, video, and text.  Chat, hang out, and stay close with your friends and communities.

Hello this has 100% been fixed in 0.1.58 I have 40000 test cases that indicate that this is now working.

So that should be fixed

**Comment by Darkere** [comment]
Yes. There was some confusion about this being the same issue. But this seems to be an unrelated issue concerning Occultism mobs.

**Comment by marchermans** [comment]
> Yes. There was some confusion about this being the same issue. But this seems to be an unrelated issue concerning Occultism mobs.

This is still a PVI issue at heart, it breaks our mod due to the heavy use of threading. There is some mod that causes an Interrupt on a thread (which might or not might be PVI, we do our best to not cause them, but you know, we are human and still might). And that closes the NIO Zip FileSystem in the classloader which is why you see a CNF Error eventhough the class is available.

**Comment by marchermans** [comment]
@Darkere, @theboo and @Joprebond I found an issue in PVI, were outside of our control we could still trigger an interrupt and cause this issue.

This comes from legacy code that we took over from minecolonies. Expect an update from both mods in the near future that fixes it.
