### ISSUE TITLE
[Suggestion] ModernFix

### ISSUE THREAD

**Issue by Gronglegrowth** [EnigmaticaModpacks/Enigmatica9#411]
### URL

https://curseforge.com/minecraft/mc-mods/modernfix

### Why would you like the mod added?

Extremely good performance and load time optimization mod. It can help vastly with ram usage if configured right, as well.

**Comment by NielsPilgaard** [comment]
I'm seeing KubeJS errors on world join after adding Modern Fix 😅

**Comment by NielsPilgaard** [comment]
It looks super promising, but this type of mod usually breaks in unforseen ways. I'm not sure we have the time to integrate it.

**Comment by Kanzaji** [comment]
> I'm seeing KubeJS errors on world join after adding Modern Fix 😅

@NielsPilgaard Are you sure those aren't just Tags exploding again 😅?

I did also suggest that mod on the contributor channel some time ago, we always have the mod developer on our discord if we have any issues 😄

**Comment by NielsPilgaard** [comment]
> > I'm seeing KubeJS errors on world join after adding Modern Fix 😅
> 
> @NielsPilgaard Are you sure those aren't just Tags exploding again 😅?

God no, not even a little sure :P I'll try some more I guess

**Comment by Darkere** [comment]
The sheer amount of mixins just guarantees things to go wrong in unexplainable ways...

**Comment by NielsPilgaard** [comment]
Yeah :/ I'm gonna pass I'm afraid.

**Comment by embeddedt** [comment]
@Darkere Out of curiosity, and with all due respect, did you test the mod in any instances and observe the approximately 2x speedup it usually provides to load times, or check for the presence of [documentation](https://github.com/embeddedt/ModernFix/wiki/Summary-of-Patches) on what exactly the mod does (with the ability to disable each patch individually)? I've noticed a general resentment towards mixin-based performance mods in the wider Minecraft community for the last couple years and am curious what sparks it.

**Comment by Darkere** [comment]
I did actually check out your documentation. And respect for that one, most performance mod authors don't bother. 

Many mods use mixins. But most of the time these mixins are as small as possible or don't change any behavior for other mods that might use the same code. 
Your Mod by design does not do that. Which means every change intentionally changes something about vanilla or other mods that the authors of that mod have no way of anticipating. 

The actual problem comes in every time there is an issue we can't directly track down. Since we can't be sure its not caused by Modern Fix we need to spend an extra 10 min relaunching the game every time just to make sure. 

Also for every bug report we would theoretically need to do the same, as reporting bugs caused by added performance mods is a great way to sour Mod dev relationships.

**Comment by embeddedt** [comment]
That's fair. Unfortunate, given the performance issues modern Minecraft versions have, but completely understandable. Thanks for your reply. :slightly_smiling_face:
