### ISSUE TITLE
Creatures and Beasts (CNB) Sporeling Bug [Overspawn + Hostile Spawn Bug]

### ISSUE THREAD

**Issue by KuryKat** [EnigmaticaModpacks/Enigmatica9#481]
### Modpack Version

1.8.1

### Describe your issue.

When my friends were playing they told me the CNB's Sporeling was spawning way too much on The Nether, I thought they were exaggerating, but then when I look onto it, it seems like it's true...

(All the white dots on the map are red sporelings)
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/57152799/1e587f65-6f20-4e31-80f0-92954df030d3)

Besides... it seems that the Warped Variation, and any of the hostile variations aren't spawning at all.... it only naturally spawns the Red Friendly ones....
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/57152799/6d6059a9-b656-4344-a25a-a5b94866cb0f)

I have spoken to HellionGames in the Bonsai Studios Discord server and they told me to try this datapack to try to partially reduce the overspawn, since it fixes BYG's biomes so they're actually adding to the Minecraft is_nether tag. Their biomes weren't properly tagged. 

``/kubejs/data/minecraft/tags/worldgen/biome/is_nether.json``
```json
{
  "replace": false,
  "values": [
    "byg:arisian_undergrowth",
    "byg:brimstone_caverns",
    "byg:crimson_gardens",
    "byg:embur_bog",
    "byg:glowstone_gardens",
    "byg:magma_wastes",
    "byg:quartz_desert",
    "byg:subzero_hypogeal",
    "byg:sythian_torrids",
    "byg:wailing_garth",
    "byg:warped_desert",
    "byg:weeping_mire"
  ]
}
```

After a small testing that I asked the players to do, it seemed to have reduced the first but just a little.

The other problem is that the hostile mob isn't spawning, at all, we tried checking the warped forest and naturally only spawns the red friendly one:

![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/57152799/d67143b1-e1c7-4979-878d-0577cf55b787)

which wasn't even supposed to spawn there, with the spawn egg it also spawns the same one:

![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/57152799/43502ff0-4305-4ea4-821a-1dda89858ddb)

I could only spawn the hostile one with commands:

![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/57152799/59972dc3-3beb-4e86-8bc0-4552ea9b3877)

The mod developer himself said that it shouldn't be a mod bug, since it's the first time they see that happening, they said that some mod, or some modification done by the modpack, seems to be overriding the "finalizeSpawn" method behavior for the Sporeling, meaning that none of the variant setting is functioning. 

I am not entirely sure this could be a bug in Enigmatica's end to be honest, creating this issue more to track it, to be honest.

Hope we manage to fix this somehow.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

@KuryKat

**Comment by Dariensg** [comment]
They pretty much covered everything (I'm the Creatures and Beasts dev). I did want to mention, my suspicion for another mod overriding the behavior of finalizeSpawn comes from a couple of tests. Natural spawning and egg spawning both don't spawn the variants they should, which happens in finalizeSpawn. Especially with egg spawning, but even with natural spawning, this shouldn't happen based on the code. Spawning it with a command setting the variant NBT, however, did work. So there isn't an issue with the data being recognized, just it being set on spawn.

I'll link the relevant method from my repo [here](https://github.com/bonsaistudi0s/Creatures_And_Beasts-Forge/blob/9af763713125f3271dcb9813df4afaf001d6c1ae/src/main/java/com/cgessinger/creaturesandbeasts/entities/SporelingEntity.java#L320). 

It's worth noting that the improperly tagged biomes from BYG is a separate, but equally relevant issue. If the spawns are added to a Nether biome with the monster category, but the biome isn't properly tagged as Nether using the Vanilla Minecraft tag, the spawn will spawn the creature variant of Sporelings as was happening here, but they will count to the creature mob cap while checking the monster cap for space, leading to potentially infinite spawns. Note that this isn't entirely what's happening here as the variant is still incorrect in the vanilla Warped Forest biome. Let me know if any more info would help!

**Comment by theboo** [comment]
yeah, i completely forgot motoko is giving these guys some fun effects through the apotheosis miniboss feature.. this is on us/apotheosis

spawn is being overwritten here(100% chance): https://github.com/EnigmaticaModpacks/Enigmatica9/blob/master/kubejs/server_scripts/base/recipes/apotheosis/minibosses/cnb.js

and the fun effects are here:
https://github.com/EnigmaticaModpacks/Enigmatica9/blob/master/kubejs/server_scripts/base/recipes/apotheosis/miniboss_gear/sporeling.js

**Comment by KuryKat** [comment]
Yeah I saw those scripts but I honestly assumed it wasn't a problem because since they refer to apotheosis bosses I'd assume it'd be *when* Apotheosis decides to spawn a Sporeling as a boss, you know? but I'm not sure if it's working, we'd need to confirm with @MuteTiefling

**Comment by theboo** [comment]
the minibosses are different than the full bosses... minibosses are the things like the forsaken knights/other custom skeletons... just normal mobs with a chance at spawning with certain effects/attributes... the actual apo boss stuff(the bosses that spawn with a sound and are highlighted in world) is all in apotheosis/bosses, not /minibosses

**Comment by Dariensg** [comment]
Yeah, that's definitely it. Their variants are stored as NBT, so that script spawning them with a set blank NBT is wiping their variant. I don't know much about scripts in this sense, but if you could take into account their NBT on spawn and incorporate it, that should fix it! Glad it was at least a pretty simple problem to find!

**Comment by Dariensg** [comment]
It is worth noting that if a Sporelings spawns are added to a Nether biome that isn't tagged correctly, it can end up in the infinite spawn issue, but that wouldn't be on you guys. I supplied the OP with a datapack that at least tags the BYG biomes correctly since the Sporelings seemed to be spawning in those, but it's just something to keep in mind in case others run into Sporelings taking over their world in the future.

**Comment by MuteTiefling** [comment]
Alright, I get why the apotheosis stuff would break the variants, but I'm not sure I understand why they're spawning too much? Is there something wrong with this?

https://github.com/EnigmaticaModpacks/Enigmatica9/blob/ad14e3318aaa9a8a146f32f970a9d5450699404f/kubejs/startup_scripts/base/worldgen/enigmatica/add_spawn.js#L39

**Comment by KuryKat** [comment]
@MuteTiefling like @Dariensg said, we assumed that the issue with them spawning too much was the fact that the BYG nether biomes weren't tagged with the vanilla minecraft is_nether, so it caused them to spawn infinitely, so we added the datapack that I provided on the post to try to partially reduce that issue, but I'm not entirely sure it has fixed completely

**Comment by KuryKat** [comment]
Some tests run by the players seems to show that they are spawning less frequently, when they first used ``/kill @e[type=cnb:sporeling]`` to clear them all to see how they'd spawn it had around 115 or more of them, the second time (after reloading with the edited datapack) after waiting for a few minutes returned that it killed 30 of them, then after 20 or so minutes the next one killed 25 of them, so it might have mitigated the issue, needs further testing to be honest, in my opinion, to make sure that the overspawn doesn't happen again

**Comment by MuteTiefling** [comment]
Ah, that's what I get for reading quick. Alright, I'll get the biomes tagged here and then look into what I can do about the apotheosis minibosses. Might need Shadows' help there.

**Comment by Shadows-of-Fire** [comment]
Alright, couple things here:

Apotheosis 6.3.0 will be including a `finalize` field [on the minibosses](https://github.com/Shadows-of-Fire/Apotheosis/blob/1.19/src/main/java/shadows/apotheosis/adventure/boss/MinibossItem.java#L174) which will allow the `SpecialSpawn` event to propagate, resulting in `Mob#finalizeSpawn` still being called.

However, a better solution would be to either split these different mob types into their own entity types (as was done with Skeletons, Wither Skeletons, and Strays in vanilla), or at least delay the type selection to first entity tick instead of in a cancelable method (since it appears that setting the type is critical, and should not rely on such mechanisms).

Another thing of note is that, because `Mob#finalizeSpawn` would be called before the miniboss is applied (with my new flag set to true), that the type would still be lost if the miniboss were to perform raw nbt application.

This is because raw NBT application uses `Entity#readAdditionalSaveData`, which normally does not update information if a specific key is absent from the tag. However, [your implementation](https://github.com/bonsaistudi0s/Creatures_And_Beasts-Forge/blob/9af763713125f3271dcb9813df4afaf001d6c1ae/src/main/java/com/cgessinger/creaturesandbeasts/entities/SporelingEntity.java#L120C1-L120C1) does not check `CompoundTag#contains` before applying.
