### ISSUE TITLE
Adding alternatives for armor/tools

### ISSUE THREAD

**Issue by Reynales** [EnigmaticaModpacks/Enigmatica9#550]
### Describe your suggestion

My suggestion is to perhaps add some new gear like bronze armor/tools or bring back the osmium and refined obsidian and simply nerf them to match iron and diamond respectively.

P.S. The chain links recipe to craft chain armor costs more overall iron than the actual iron armor while being worse

### Why would you like this added/changed?

So I noticed the osmium and refined obsidian gear sets from mekanism were removed and I can understand why seeing as they are quite strong, pretty much invalidating other armor options. But this makes access to armor early game a bit of an issue seeing as iron is used in so many recipes and using up 36 of it to craft a full set I feel is quite steep. Especially since in E9 the only ore doubling you can do is with occultism crusher spirit which takes a decent amount of setup to acquire and is very slow on top of that.

**Comment by MuteTiefling** [comment]
The current ore doubling situation is a bug and has been fixed for next release already. https://github.com/EnigmaticaModpacks/Enigmatica9/issues/539

I can certainly look at making Chain armor cheaper. You're right it's a little silly if it costs more than Iron

As for the rest, I feel like it becomes a fair bit less relevant with the two above issues addressed. Yes? Otherwise there's Leather or the Ars Sets which would allow you to spend your iron on other things. The Hexerei set is comparable to Diamond too, while offering exceptional magic resistance. 

There's also a very large variety available as drops from tougher mobs, or from loot chests. Just try to pick your loot locations carefully... the big dungeons are going to be deadly early on. But the ones you find while caving will be considerably safer.
