### ISSUE TITLE
Create Recipes Missing

### ISSUE THREAD

**Issue by itanne99** [EnigmaticaModpacks/Enigmatica9#579]
### Modpack Version

1.10.0

### Describe your issue.

The following items no longer have recipes, or EMI does not read modified recipes.

- Shaft
- Nozzle
- Hand crank
- Crushing wheel
- Basin
- Depot
- Wooden Bracket
- Metal Bracket
- Steam Engine
- Cart Assembler
- Linear Chassis
- Radial Chassis
- Mechanical Plough
- Mechanical Drill
- Mechanical Harvester
- Andesite Casings

Lots of other items as well.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by theboo** [comment]
Whoops, yup we're hiding andesite alloy in normal mode... These recipes should still work just can't see them because they have a hidden item lol..

As a temporary fix, deleting the following line, saving the file, then doing f3+t in game should make all these recipes show up again: https://github.com/EnigmaticaModpacks/Enigmatica9/blob/460672782bda29495c53f247715a81ee751c1251/kubejs/client_scripts/base/emi_material_unification.js#L104

**Comment by itanne99** [comment]
Workaround for the issue has been provided by @theboo

**Comment by MuteTiefling** [comment]
Probably hotfix worthy.

**Comment by NielsPilgaard** [comment]
Agreed 👍 I'll release a hotfix within 2 hours.
