### ISSUE TITLE
Missing World Generation Info for certain ores / Ores not showing in JEI

### ISSUE THREAD

**Issue by pazi146** [EnigmaticaModpacks/Enigmatica9#677]
### Modpack Version

1.12.1

### Describe your issue.

The following ores don't have worldgen information listed in JEI (rightclick on ore):
- Ancient Debris
- Gold Ore
- Copper Ore
- Iron Ore

Additionally certain ores list the information but don't show up in JEI:
- Coal Ore
- Redstone Ore
- Nether Quartz Ore
- Bitumen Ore

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Thanks for the report!

@Kanzaji could you have a look at this please? 😃

**Comment by Kanzaji** [comment]
Okay so, Ancient Debris isn't generated iirc from EE, so that is why it doesn't contain EE Generation info 😅

However for the other stuff.... ym... I have no idea what happened >.> I am fairly sure it worked back when we had JEI, and I didn't touch EMI yet at all 😅

Will try to experiment with this tomorrow, it might be either incompatibilities or some broken script, but I have zero idea at this moment >.>

**Comment by Kanzaji** [comment]
Okay so from what I can tell, here is some statistics for tomorrow's debuggin session 😄
# Missing Ore in EMI
- Coal Ore
- Lapis Ore
- Nether Quartz Ore
- Redstone Ore
- EE Bitumen ore (Sand still shows up)
# Missing information
- Copper
- Dimensional Geode
- Fluorite geode
- Sulfur Geode
- Gold
- Iron

**Comment by Kanzaji** [comment]
### Okay so update time!
- Mising ores from EMI were fixed, they show up now correctly and world gen information for them works \o/
- Missing information for geodes will not be fixed for now 😢 The feature is not yet implemented in EE, so this will have to wait for Rid to have some time to work on EE 😅
- Mising information for Copper/Gold/Iron is going to be fixed with the removal of EE Vanilla ingots/nuggets/blocks and raw materials, however this is impossible to do currently until a crash when crushed ore is present without an ingot, the patch is made and I'm just waiting for Rid to look at it 😄
The link to the PR: https://github.com/Ridanisaurus/EECreateAddon/pull/4

**Comment by Kanzaji** [comment]
Update!
Rid has merged mine PR with the Crash fix, so I'm going back to work on this issue and removal of Vanilla Ingot replacements!
(What means I think I did everything back in August and just need to make sure and do a PR 😄)
