### ISSUE TITLE
[e9e] Queen Bee asks for unobtainable gold leaves

### ISSUE THREAD

**Issue by Nidaelie** [EnigmaticaModpacks/Enigmatica9#694]
### Modpack Version

1.12.1

### Describe your issue.

Trying to get golden leaves to feed the queen bee...

recipe shows natures shears rclicking the leaves to get them...

the tool gets dur dmg but no leaves at all

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Nidaelie** [comment]
silk touch on leaves drops golden leaf

**Comment by Nidaelie** [comment]
i need leaves not leafs... i need them to feed the wueen bee... not dropping

**Comment by MuteTiefling** [comment]
As far as I'm aware, there's no way to get the gold leaf block, and that's intended. The Queen Bee is just asking for things in a tag. 

I'll see if we can do anything about blacklisting them so they don't show up.

**Comment by Nidaelie** [comment]
almost all things she ask are unobtainables in this phase.... biomes o
plenty flowers... or saplings....

**Comment by Nidaelie** [comment]
Sorry my bad, from the otbyg mod

**Comment by MuteTiefling** [comment]
They're obtainable. Just maybe not for you at your stage. That's considerably different from the gold leaves where you're never meant to be able to pick them up as a block, ever. 

Besides, these are *optional* bonus trades. Just because you don't have the item she really wants doesn't mean she won't trade at all.
