### ISSUE TITLE
E9E Blaze burner + straw not igniting when getting lava througth pipes

### ISSUE THREAD

**Issue by Nidaelie** [EnigmaticaModpacks/Enigmatica9#697]
### Modpack Version

1.12.1

### Describe your issue.

Trying to use a blaze burner for a steam engine but when i use a straw on burned to accept liquids directly from pipes it doesnt ignite.... accepts de lava from the pipe but not consuming it so it doesnt extra heat. clicking a lava bucket on it makes it ignite....

Once the burner has an internal b of lava should ignite

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NielsPilgaard** [comment]
Why'd you close this issue? :)

**Comment by Nidaelie** [comment]
Realized that there is no recipe for lava for straws... but clicking with a
lava bucket still works

**Comment by Unarelith** [comment]
Hello, I think this issue might be reopened, I have the exact same problem on E9E 1.20.1.

If lava is supposed to work, both right-clicking with a filled bucket and sending lava through pipes should work.
If lava isn't supposed to work it might be important to tell this in the quest book because this would be counterintuitive. And of course, in that case, lava buckets shouldn't work, and blaze burner shouldn't accept lava fluid at all.
But maybe there's limitations from the mod preventing this?

In any case, I think it might be important to have more details on the issue here in case it happens to other players

**Comment by MuteTiefling** [comment]
I think I'll leave it as is. I don't much care for the idea of a blaze delicately slurping up lava through a straw and removing lava as a burnable fuel for furnaces may well break some things for others. 

If you want to use lava, you'll have to work for it a little bit. Just like you need to work a bit for the liquid fuels.

**Comment by Unarelith** [comment]
The issue is that it's not really clear which fuel you need to use, nothing about them in the quest book and the block still accepts lava buckets so it feels like it's not working properly.

As a player, here's what I did:
- Put down a Blaze Burner with a straw
- Right-click on it with a lava bucket, it works
- Input lava from pipes, it doesn't work
- Tried with different pipes, still won't work, tried different tanks, same

It was my first time using a Blaze Burner so I was pretty sure it was a bug until I came here.
Maybe this could be a nice addition to the quest book, like "lava won't work but X will"?

**Comment by MuteTiefling** [comment]
All of the fuels are very clearly indicated in EMI if you look at uses for the straw. 

They also show up if looking at uses for the Blaze Burner itself. 

![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/9543430/7e6835e1-437a-4e70-9927-537ded61f6d9)

**Comment by Unarelith** [comment]
Since it was my first time using this block, I didn't know it was possible to see the fuels like this so thanks for the tip.

However, I still think that a mention is needed in the quest book to explain this counter-intuitive "feature", like "the Blaze Burner can work with lava buckets due to a limitation but won't work with lava fluid piped into it, this is intended".

**Comment by MuteTiefling** [comment]
We generally avoid making specific references to recipes that are stated in EMI, but I'll add a note on how to see the appropriate fuels.
