### ISSUE TITLE
Suggestion to add Ars Energistique.

### ISSUE THREAD

**Issue by Kevin-Marsh** [EnigmaticaModpacks/Enigmatica9#700]
### URL

https://www.curseforge.com/minecraft/mc-mods/ars-energistique

### Why would you like the mod added?

Ars energistique provides source storage and logistics within Applied energistics.

**Comment by MuteTiefling** [comment]
Looks interesting, but I don't think this would work out well.

- We already have source based power.
- Source can already be stored in ae2 as a liquid.
- We've already added support for certus.

So that leaves a very limited number of features that this mod would add, and it doesn't really seem worth the trouble of integration.
