### ISSUE TITLE
(re)add a recipe for the Novice Spellbook

### ISSUE THREAD

**Issue by flece** [EnigmaticaModpacks/Enigmatica9#862]
### Describe your suggestion

i like that you need that book for creating more. maybe with enchanting apparatus or with Imbuement chamber.
* Antique Ink
* all essences 

### Why would you like this added/changed?

on a public Server (Ver: 1.18.0) i only got 1 Book from Lich and i need 4 books for my playstyle

**Comment by MuteTiefling** [comment]
I'll give this some consideration. I recall removing it because it was causing a lot of confusion (how do I crush for progression when I can't craft a book?)

Now that it's showing as a drop from the Lich in EMI that may be less of an issue, but it's still very likely to cause this sort of "but it's cyclical" reactions and I'd like to avoid that.
