### ISSUE TITLE
Create compacting broken for lead blocks/Supplementaries config resetting on world load

### ISSUE THREAD

**Issue by luxidoptera** [EnigmaticaModpacks/Enigmatica9#978]
### Modpack Version

I believe 1.22.1, though I'm not sure as the version number isn't listed anywhere ingame or in PrismLauncher

### Describe your issue.

I'm currently experiencing an issue where my automated ore crushing/washing/compacting setup in Create cannot make lead blocks, because the Supplementaries lead trapdoor recipe overrides the lead block recipe. I can't fix this with filters on the basin, for multiple reasons: A, this problem also applies to silver and netherite, and B, this is a multi-metal setup and applying a lead block filter makes compacting stop working for all other metals.

A secondary issue to this is preventing me from just fixing the issue myself- as a result of what I believe to be a greater issue with configs in this modpack, attempting to turn off the Lead Trapdoor (as well as the netherite and silver equivalents) through the Supplementaries config just doesn't work, as changes I made are immediately reverted upon loading the world. I've also encountered this in the past while trying to manually edit the disabled items list- though that being reverted on world load makes more sense, and isn't relevant to my problem.

This is very frustrating and essentially means almost all lead I put into my system is immediately wasted, and I can't seem to fix it on my own.

### Latest Log

https://gist.github.com/luxidoptera/7e427f0552102e7b9f95aa12087f4efb

### Have you modified the modpack?

Yes

### User Modifications

I've added the following mods and their dependencies:
Dragon Survival, Tetra, Tetranomicon, FTB Ultimine, FTB Essentials, Abnormals Delight, Atmospheric, Environmental, Aquaculture 2, Upgrade Aquatic, The Endergetic Update, JourneyMap, Macaw's Bridges, Crafting Tweaks, Mouse Tweaks. 

However I don't think any of these are relevant to my issue.

I can't make any changes to the configs of mods already included in the pack, as described above.

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Hey there, thanks for the report. 

Create has a filter that allows you to set multiple items. This will resolve your issue with your compressing setup and is the intended way to deal with recipe selection for that craft. There are two, in fact: 
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/9543430/b4fb2408-f9b6-4e65-94c5-b3eb0b9e064e)

The List Filter would allow you to set multiple recipes to handle each block: 
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/9543430/fda6fe0b-691b-4c02-b285-4e7e3805464b)

While the Attribute Filter would allow you to filter broadly on the shared `#forge:storage_blocks` tag. 



As for editing the configs, I'm not having any trouble modifying them. If you edit them while the game is open, you'll sometimes encounter issues where the mod immediately re-writes the default config due to the file being inaccessible. But, if you edit them while the game is fully closed, then launch the game, you shouldn't have any issues.

Do note many of our configs are controlled by Config Swapper due to the fact this pack hosts both a Normal and Expert mode. Supplementaries is not subject to this control, but it may account for your difficulties with other configs.


I'll go ahead and close this out as they aren't bugs with the pack. If you continue to have problems with configs, try reinstalling the pack and testing without all of the additional mods.
